Configuration:
  status: warn

  Properties: # 定义全局变量
    Property: # 缺省配置（用于开发环境）。其他环境需要在VM参数中指定，如下：
      #测试：-Dlog.level.console=warn -Dlog.level.elasticsearch=trace
      #生产：-Dlog.level.console=warn -Dlog.level.elasticsearch=info
      - name: log.level.console
        value: trace
      - name: log.level.elasticsearch
        value: trace
      - name: log.path
        value: D:/logs/iot-elasticsearch
      - name: project.name
        value: iot-elasticsearch
      - name: log.pattern
        value: %d{yyyy-MM-dd HH:mm:ss,SSS}:%4p %t (%F:%L) - %m%n
#      - name: log.file.pattern
#        value: ${log.path}/$${date:yyyy-MM}/${project.name}-%d{yyyy-MM-dd}-%i.log.zip
      - name: log.max.size
        value: 128 MB



  Appenders:
    Console:  #输出到控制台
      name: CONSOLE
      target: SYSTEM_OUT
      ThresholdFilter:
        level: ${sys:log.level.console} # “sys:”表示：如果VM参数中没指定这个变量值，则使用本文件中定义的缺省全局变量值
        onMatch: ACCEPT
        onMismatch: DENY
      PatternLayout:
        pattern: "%d{yyyy-MM-dd HH:mm:ss,SSS}:%4p %t (%F:%L) - %m%n"
    RollingFile: # 输出到文件，超过128MB归档
      - name: ROLLING_FILE
        ignoreExceptions: false
        fileName: ${log.path}/${project.name}.log
        filePattern: ${log.path}/$${date:yyyy-MM}/${project.name}-%d{yyyy-MM-dd}-%i.log.zip
        PatternLayout:
          pattern: "%d{yyyy-MM-dd HH:mm:ss,SSS}:%4p %t (%F:%L) - %m%n"
        Policies:
          SizeBasedTriggeringPolicy:
            size: ${log.max.size}
        DefaultRolloverStrategy:  # DefaultRolloverStrategy属性如不设置，则默认为最多同一文件夹下7个文件
          max: 1000

  Loggers:
    Root:
      level: info
      AppenderRef:
        - ref: CONSOLE
        - ref: ROLLING_FILE
    Logger: # 为 com.thinkgem.elclient.elasticsearch 包配置特殊的Log级别，方便调试
      - name: com.thinkgem.elclient.elasticsearch
        additivity: false
        level: ${sys:log.level.elasticsearch}
        AppenderRef:
          - ref: CONSOLE
          - ref: ROLLING_FILE